name: fyp_namaste_events
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  # Add these dependencies
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.1.0

  # Utility packages
  http: ^1.3.0
  intl: ^0.20.0
  logger: ^2.0.1
  google_fonts: ^6.2.1

  flutter_rating_bar: ^4.0.1 # Check for the latest version
  table_calendar: ^3.2.0
  # Icons
  iconsax: ^0.0.8

  provider: ^6.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  file_picker: ^10.0.0
  path: ^1.9.0
  shared_preferences: ^2.5.2
  jwt_decoder: ^2.0.1
  image_picker: ^1.1.2
  google_maps_flutter: ^2.10.1
  flutter_slidable:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/login.JPG
    - assets/onboarding1.JPG
    - assets/onboarding2.JPG
    - assets/onboarding3.JPG
    - assets/namaste eventslogo.png
    - assets/splashscreenbg.jpeg
    - assets/furthermore.JPG
    - assets/decorartion.png
    - assets/eventvenue.png
    - assets/food.png
    - assets/photography.png
  # Remove these lines if they exist:
  # firebase_core: ^x.x.x
  # firebase_auth: ^x.x.x
  # cloud_firestore: ^x.x.x
  # firebase_storage: ^x.x.x
