name: fyp_namaste_events
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.1.0
  http: ^1.3.0
  intl: ^0.18.0
  logger: ^2.0.1
  google_fonts: ^6.2.1
  flutter_rating_bar: ^4.0.1
  table_calendar: ^3.0.9
  iconsax: ^0.0.8
  provider: ^6.0.0
  cupertino_icons: ^1.0.8
  file_picker: ^10.1.9 # Updated to latest version
  path: ^1.9.0
  shared_preferences: ^2.5.2
  jwt_decoder: ^2.0.1
  image_picker: ^1.1.2
  google_maps_flutter: ^2.10.1
  khalti_flutter: ^3.0.0
  flutter_slidable: ^3.0.1  # Added version number


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/login.JPG
    - assets/onboarding1.JPG
    - assets/onboarding2.JPG
    - assets/onboarding3.JPG
    - assets/namaste eventslogo.png
    - assets/splashscreenbg.jpeg
    - assets/furthermore.JPG
    - assets/decorartion.png
    - assets/eventvenue.png
    - assets/food.png
    - assets/photography.png
